# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Priyam Parashar
shorttitle:       'PP'
tagline:          'Webpage'
description:      'Personal and Research Webpage'
baseurl:          /
avatar:           /me.png

author:
  name:           'Priyam Parashar'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde