# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Priyam Parashar
shorttitle:       'PP'
tagline:          'Homepage'
# description:      'Personal and Research Webpage'
baseurl:          'https://acsweb.ucsd.edu/~pparasha/'
url:              'https://acsweb.ucsd.edu/~pparasha/'
avatar:           'https://acsweb.ucsd.edu/~pparasha/me.png'

author:
  name:           'Priyam Parashar'
#  url:            

paginate:         5
paginate_path:    '/blog/'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde